# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f58a1db358d99f0cececb7403454791e"
name = "[DEMO] Checkout Extensions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
dev_store_url = "mackiec-checkout-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,read_products,write_products,write_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://admin.shopify.com/" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
