# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "98db8bd7e0cfaf648c0305ca50afc397"
name = "extensions-dev"
application_url = "https://mackiec-extension--development.gadget.app/shopify/install"
embedded = true

[build]
dev_store_url = "mackiec-checkout-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mackiec-extension--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
