# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "mackiec-extensions-prod"
client_id = "f58a1db358d99f0cececb7403454791e"
application_url = "https://mackiec-extension.gadget.app/shopify/install"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mackiec-extension.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "mackiec-extensions-dev.myshopify.com"
