# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f58a1db358d99f0cececb7403454791e"
name = "extensions-dev"
application_url = "https://mackiec-extension.gadget.app/shopify/install"
embedded = true

[build]
dev_store_url = "mackiec-checkout-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mackiec-extension.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
