# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
name = "Pre-Purchase Extension"
handle = "pre-purchase-ext"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "product_id"
type = "single_line_text_field"
name = "Product ID"
description = "Enter the ID of the product to recommend (e.g., 123456789)"

[[extensions.settings.fields]]
key = "text_appearance"
type = "single_line_text_field"
name = "Text Appearance"
description = "Choose the text appearance"
default = "subdued"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"base\", \"accent\", \"decorative\", \"interactive\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\", \"monochrome\"]"

# Text Configuration
[[extensions.settings.fields]]
key = "section_heading"
type = "single_line_text_field"
name = "Section Heading"
description = "Heading text for the product recommendation section."
default = "You might also like"

[[extensions.settings.fields]]
key = "add_button_text"
type = "single_line_text_field"
name = "Add Button Text"
description = "Text for the add to cart button."
default = "Add"

[[extensions.settings.fields]]
key = "error_message"
type = "single_line_text_field"
name = "Error Message"
description = "Message shown when there's an issue adding the product."
default = "There was an issue adding this product. Please try again."
