# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
name = "Product Customiser UI"
handle = "product-customiser-ui"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.cart-line-item.render-after"

[extensions.settings]
[[extensions.settings.fields]]
key = "checkbox_text"
type = "single_line_text_field"
name = "Checkbox Text"
description = "Text to display next to the checkbox"
default = "Yes, add custom embroidery for small fee."

[[extensions.settings.fields]]
key = "text_appearance"
type = "single_line_text_field"
name = "Text Appearance"
description = "Choose the text appearance"
default = "subdued"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"base\", \"accent\", \"decorative\", \"interactive\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\", \"monochrome\"]"

# Additional Text Configuration
[[extensions.settings.fields]]
key = "banner_title"
type = "single_line_text_field"
name = "Banner Title"
description = "Title for the warning banner when attributes cannot be updated."
default = "Product Customiser"

[[extensions.settings.fields]]
key = "text_field_label"
type = "single_line_text_field"
name = "Text Field Label"
description = "Label for the custom text input field."
default = "Your Custom Text"

[[extensions.settings.fields]]
key = "max_characters_error"
type = "single_line_text_field"
name = "Max Characters Error"
description = "Error message when character limit is exceeded."
default = "Max 25 characters, please"

[[extensions.settings.fields]]
key = "character_counter_suffix"
type = "single_line_text_field"
name = "Character Counter Suffix"
description = "Suffix text for the character counter (e.g., '/25')."
default = "/25"
