# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
name = "Custom Content Block"
handle = "custom-content-block"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
description = "Enter a title for the content block"
default = "Important Information"

[[extensions.settings.fields]]
key = "content"
type = "multi_line_text_field"
name = "Content"
description = "Enter the content for the block"
default = "This is some important information about your order."

[[extensions.settings.fields]]
key = "icon"
type = "single_line_text_field"
name = "Icon"
description = "Choose an icon for the content block"
default = "info"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"arrowLeft\", \"arrowRight\", \"arrowUp\", \"arrowUpRight\", \"arrowDown\", \"bag\", \"bullet\", \"calendar\", \"camera\", \"caretDown\", \"cart\", \"cashDollar\", \"categories\", \"checkmark\", \"chevronLeft\", \"chevronRight\", \"chevronUp\", \"chevronDown\", \"clock\", \"close\", \"creditCard\", \"critical\", \"delete\", \"delivered\", \"delivery\", \"disabled\", \"discount\", \"email\", \"error\", \"errorFill\", \"external\", \"filter\", \"geolocation\", \"gift\", \"giftFill\", \"grid\", \"hamburger\", \"hollowCircle\", \"horizontalDots\", \"image\", \"info\", \"infoFill\", \"list\", \"lock\", \"magnify\", \"map\", \"marker\", \"minus\", \"mobile\", \"note\", \"orderBox\", \"pen\", \"plus\", \"profile\", \"question\", \"questionFill\", \"reorder\", \"return\", \"savings\", \"settings\", \"star\", \"starFill\", \"starHalf\", \"store\", \"success\", \"truck\", \"upload\", \"verticalDots\", \"warning\", \"warningFill\"]"

[[extensions.settings.fields]]
key = "title_size"
type = "single_line_text_field"
name = "Title Size"
description = "Choose the title size"
default = "medium"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"small\", \"medium\", \"large\"]"

[[extensions.settings.fields]]
key = "icon_appearance"
type = "single_line_text_field"
name = "Icon Appearance"
description = "Choose the icon appearance"
default = "accent"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"base\", \"accent\", \"decorative\", \"interactive\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\", \"monochrome\"]"

[[extensions.settings.fields]]
key = "is_collapsible"
type = "boolean"
name = "Make Content Collapsible"
description = "Enable collapsible content block"
default = false

[[extensions.settings.fields]]
key = "image"
type = "single_line_text_field"
name = "Image URL"
description = "Provide an image URL to display in the content block"
