# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "Delivery Date Picker"
handle = "delivery-date-ext"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
target = "purchase.checkout.shipping-option-list.render-after"
module = "./src/Checkout.jsx"
export = "purchaseCheckoutShippingOptionListRenderAfter"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

[[extensions.metafields]]
namespace = "custom"
key = "show_date_picker"
[[extensions.metafields]]
namespace = "custom"
key = "delivery_date"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
description = "Enter a title for the banner"
default = "Not going to be at home?"

[[extensions.settings.fields]]
key = "description"
type = "single_line_text_field"
name = "Description"
description = "Enter a description for the banner"
default = "Yes - I'll choose a delivery date."

[[extensions.settings.fields]]
key = "banner_status"
type = "single_line_text_field"
name = "Banner Status"
description = "Choose the banner status"
default = "info"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"info\", \"success\", \"warning\", \"critical\"]"

[[extensions.settings.fields]]
key = "icon"
type = "single_line_text_field"
name = "Icon"
description = "Choose an icon for the banner"
default = "truck"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"arrowLeft\", \"arrowRight\", \"arrowUp\", \"arrowUpRight\", \"arrowDown\", \"bag\", \"bullet\", \"calendar\", \"camera\", \"caretDown\", \"cart\", \"cashDollar\", \"categories\", \"checkmark\", \"chevronLeft\", \"chevronRight\", \"chevronUp\", \"chevronDown\", \"clock\", \"close\", \"creditCard\", \"critical\", \"delete\", \"delivered\", \"delivery\", \"disabled\", \"discount\", \"email\", \"error\", \"errorFill\", \"external\", \"filter\", \"geolocation\", \"gift\", \"giftFill\", \"grid\", \"hamburger\", \"hollowCircle\", \"horizontalDots\", \"image\", \"info\", \"infoFill\", \"list\", \"lock\", \"magnify\", \"map\", \"marker\", \"minus\", \"mobile\", \"note\", \"orderBox\", \"pen\", \"plus\", \"profile\", \"question\", \"questionFill\", \"reorder\", \"return\", \"savings\", \"settings\", \"star\", \"starFill\", \"starHalf\", \"store\", \"success\", \"truck\", \"upload\", \"verticalDots\", \"warning\", \"warningFill\"]"

[[extensions.settings.fields]]
key = "background_appearance"
type = "single_line_text_field"
name = "Background Appearance"
description = "Choose the background appearance"
default = "subdued"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"transparent\", \"base\", \"subdued\"]"

[[extensions.settings.fields]]
key = "icon_appearance"
type = "single_line_text_field"
name = "Icon Appearance"
description = "Choose the icon appearance"
default = "monochrome"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"base\", \"accent\", \"decorative\", \"interactive\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\", \"monochrome\"]"

[[extensions.settings.fields]]
key = "text_appearance"
type = "single_line_text_field"
name = "Text Appearance"
description = "Choose the text appearance"
default = "accent"
  [[extensions.settings.fields.validations]]
  name = "choices"
  value = "[\"base\", \"accent\", \"decorative\", \"interactive\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\", \"monochrome\"]"
