api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "Custom Stored Selection"
handle = "custom-stored-selection"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"
export = "checkoutBlock"

[extensions.capabilities]
api_access = true
block_progress = true
network_access = false

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

[extensions.settings]
  [[extensions.settings.fields]]
  key = "title_1"
  type = "single_line_text_field"
  name = "Option One | Section Title"
  description = "Enter a title for the section."
  [[extensions.settings.fields]]
  key = "description_1"
  type = "multi_line_text_field"
  name = "Option One | Section Content"
  description = "Provide your text content."
  [[extensions.settings.fields]]
  key = "image_1"
  type = "single_line_text_field"
  name = "Option One | Image to Display"
  description = "Provide an image URL to display."

  [[extensions.settings.fields]]
  key = "title_2"
  type = "single_line_text_field"
  name = "Option Two | Section Title"
  description = "Enter a title for the section."
  [[extensions.settings.fields]]
  key = "description_2"
  type = "multi_line_text_field"
  name = "Option Two | Section Content"
  description = "Provide your text content."
  [[extensions.settings.fields]]
  key = "image_2"
  type = "single_line_text_field"
  name = "Option Two | Image to Display"
  description = "Provide an image URL to display."
  
  [[extensions.settings.fields]]
  key = "title_3"
  type = "single_line_text_field"
  name = "Option Three | Section Title"
  description = "Enter a title for the section."
  [[extensions.settings.fields]]
  key = "description_3"
  type = "multi_line_text_field"
  name = "Option Three | Section Content"
  description = "Provide your text content."
  [[extensions.settings.fields]]
  key = "image_3"
  type = "single_line_text_field"
  name = "Option Three | Image to Display"
  description = "Provide an image URL to display."
