# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "Custom Field Validation | VAT or Age"
handle = "custom-field-validation"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/targets-overview
[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"
[extensions.capabilities]
block_progress = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "fieldTitle"
type = "single_line_text_field"
name = "Field Heading"
description = "Specify the title of the field input."
[[extensions.settings.fields]]
key = "showVatNumberField"
type = "boolean"
name = "Show VAT Number Field"
description = "Choose whether to show a VAT number field instead of the age field."
[[extensions.settings.fields]]
key = "ageTarget"
type = "single_line_text_field"
name = "Target Age"
description = "Optional: Enter an Age at which to block checkout progress. Default state is 18."

# Field Labels
[[extensions.settings.fields]]
key = "age_field_label"
type = "single_line_text_field"
name = "Age Field Label"
description = "Label for the age input field."
default = "Your age"

[[extensions.settings.fields]]
key = "age_field_label_optional"
type = "single_line_text_field"
name = "Age Field Label (Optional)"
description = "Label when age field is optional."
default = "Your age (optional)"

[[extensions.settings.fields]]
key = "vat_field_label"
type = "single_line_text_field"
name = "VAT Field Label"
description = "Label for the VAT number input field."
default = "VAT Number"

[[extensions.settings.fields]]
key = "vat_field_label_optional"
type = "single_line_text_field"
name = "VAT Field Label (Optional)"
description = "Label when VAT field is optional."
default = "VAT Number (optional)"

# Validation Error Messages
[[extensions.settings.fields]]
key = "age_required_error"
type = "single_line_text_field"
name = "Age Required Error"
description = "Error message when age is required but not entered."
default = "Enter your age"

[[extensions.settings.fields]]
key = "age_too_young_error"
type = "multi_line_text_field"
name = "Age Too Young Error"
description = "Error message when customer is too young to purchase."
default = "You're not legally old enough to buy some of the items in your cart."

[[extensions.settings.fields]]
key = "vat_required_error"
type = "single_line_text_field"
name = "VAT Required Error"
description = "Error message when VAT number is required but not entered."
default = "VAT number is required"

[[extensions.settings.fields]]
key = "vat_invalid_error"
type = "single_line_text_field"
name = "VAT Invalid Error"
description = "Error message when VAT number format is invalid."
default = "Invalid VAT number"